---
title: "Deliverable2"
output: html_notebook
---

install packages for analysis
```{r}
installed.packages("rio")
installed.packages("ggplot2")
installed.packages("DescTools")
installed.packages("dplyr")
```

```{r}
library(rio)
install_formats()
rm(list = ls())

library(ggplot2)
library(DescTools)
library(dplyr)
```

Getting the data TABLE from the file
```{r}
link='https://github.com/superadlerrrk/543/blob/main/Deliverable1/Crime_Data.csv?raw=true'
crime = import(link)

crime$grouped_time <- cut(crime$"Occurred Time", 
      breaks = c(0, 1, 559, 1159, 1759, 2359),
      labels = c("Unknown", "Midnight", "Morning", "Afternoon", "Evening"),
      include.lowest = TRUE)

table(crime$Precinct, crime$grouped_time)

# Get the counts of each group in grouped_time
time_counts <- table(crime$grouped_time)
```

Plot a bar plot
```{r}
barplot(time_counts, 
        main = "Occurrences by Time of Day", 
        xlab = "Time of Day", 
        ylab = "Count")

ggplot(crime, aes(x = grouped_time, fill = Precinct)) + 
  geom_bar() + 
  labs(x = "Grouped Occurred Time", y = "Count of Entries")

crime$offense_category <- gsub("-.*", "", crime$`Primary Offense Description`)

off_ctgr <- unique(crime$`offense_category`)
```

Create a data frame with the count of entries by offense category
```{r}
offense_counts <- data.frame(table(crime$offense_category))
```

Sort the offense categories by count of entries in descending order
```{r}
sorted_offenses <- offense_counts[order(offense_counts$Freq, decreasing = TRUE), ]
```

Select the top 10 offense categories by count of entries
```{r}
top_10_offenses <- head(sorted_offenses, 10)
```

Create a bar plot of the top 10 offense categories
```{r}
ggplot(top_10_offenses, aes(x = reorder(Var1, Freq), y = Freq, fill = Var1)) +
  geom_col() +
  xlab("Offense Category") +
  ylab("Count of Entries") +
  ggtitle("Top 10 Offense Categories by Count of Entries") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```